# Site settings
title: Hudson Taylor
tagline: A library for building awesome microservices
description: A library for building awesome microservices
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hudson-taylor.github.io/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: hudson-taylor

# Build settings
markdown: redcarpet
# markdown: kramdown
highlighter: pygments

redcarpet:
  extensions: ['tables', 'no_intra_emphasis', 'autolink', 'with_toc_data']

# kramdown:
#   input: GFM
#   hard_wrap: false

# Blog Settings
permalink: /blog/:year/:month/:day/:title
paginate: 1

gems:
  - jekyll-redirect-from
